[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "false"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
